apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - resources:
            requests:
              cpu: "200m"
          env:
          - name: jasypt.encryptor.password
            valueFrom:
              configMapKeyRef:
                key: AUTH_JASYPT_KEY
                name: cloudnine-env
          - name: management.zipkin.tracing.endpoint
            valueFrom:
              configMapKeyRef:
                key: ZIPKIN_URI
                name: cloudnine-env
          - name: eureka.client.service-url.defaultZone
            valueFrom:
              configMapKeyRef:
                key: EUREKA_URI
                name: cloudnine-env
          - name: spring.profiles.active
            value: "dev"
          name: auth
          image: fosong98/authservice:0.0.29
          ports:
            - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 20
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 20

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: auth-boot-hpa
  labels:
    app: auth-boot-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auth-deployment
  minReplicas: 1
  maxReplicas: 3

  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        AverageUtilization: 50
        type: Utilization
