apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - env:
          - name: management.zipkin.tracing.endpoint
            valueFrom:
              configMapKeyRef:
                key: ZIPKIN_URI
                name: cloudnine-env
          - name: eureka.client.service-url.defaultZone
            valueFrom:
              configMapKeyRef:
                key: EUREKA_URI
                name: cloudnine-env
          name: auth
          image: fosong98/authservice:23
          ports:
            - containerPort: 8081
