apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - env:
          - name: management.zipkin.tracing.endpoint
            valueFrom:
              configMapKeyRef:
                key: ZIPKIN_URI
                name: cloudnine-env
          name: auth
          image: fosong98/authservice:t1
          ports:
            - containerPort: 8081
