apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-deployment
  labels:
    app: store
spec:
  replicas: 2
  selector:
    matchLabels:
      app: store
  template:
    metadata:
      labels:
        app: store
    spec:
      containers:
      - env:
        - name: jasypt.encryptor.password
          valueFrom:
            configMapKeyRef:
              key: store.jasypt.encryptor.password
              name: cloudnine-env
        name: store
        image: fosong98/storeservice:3
        ports:
        - containerPort: 8084
