apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-deployment
  labels:
    app: store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store
  template:
    metadata:
      labels:
        app: store
    spec:
      containers:
      - env:
        - name: jasypt.encryptor.password
          valueFrom:
            configMapKeyRef:
              key: store.jasypt.encryptor.password
              name: cloudnine-env
        - name: management.zipkin.tracing.endpoint
          valueFrom:
            configMapKeyRef:
              key: ZIPKIN_URI
              name: cloudnine-env
        - name: AUTH_SERVICE_URI
          valueFrom:
            configMapKeyRef:
              key: AUTH_SERVICE_URI
              name: cloudnine-env
        name: store
        image: fosong98/storeservice:t10
        ports:
        - containerPort: 8084
