apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-deployment
  labels:
    app: store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store
  template:
    metadata:
      labels:
        app: store
    spec:
      containers:
      - env:
        - name: jasypt.encryptor.password
          valueFrom:
            configMapKeyRef:
              key: STORE_JASYPT_KEY
              name: cloudnine-env
        - name: management.zipkin.tracing.endpoint
          valueFrom:
            configMapKeyRef:
              key: ZIPKIN_URI
              name: cloudnine-env
        - name: AUTH_SERVICE_URI
          valueFrom:
            configMapKeyRef:
              key: AUTH_SERVICE_URI
              name: cloudnine-env
        - name: USER_SERVICE_URI
          valueFrom:
            configMapKeyRef:
              key: USER_SERVICE_URI
              name: cloudnine-env
        - name: CREDIT_SERVICE_URI
          valueFrom:
            configMapKeyRef:
              key: CREDIT_SERVICE_URI
              name: cloudnine-env
        - name: eureka.client.service-url.defaultZone
          valueFrom:
            configMapKeyRef:
              key: EUREKA_URI
              name: cloudnine-env
        name: store
        image: fosong98/storeservice:0.0.2
        ports:
        - containerPort: 8084
