apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-deployment
  labels:
    app: credit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: credit
  template:
    metadata:
      labels:
        app: credit
    spec:
      containers:
      - env:
        - name: jasypt.encryptor.password
          valueFrom:
            configMapKeyRef:
              key: credit.jasypt.encryptor.password
              name: cloudnine-env
        - name: management.zipkin.tracing.endpoint
          valueFrom:
            configMapKeyRef:
              key: ZIPKIN_URI
              name: cloudnine-env
        name: credit
        image: fosong98/creditservice:t1
        ports:
        - containerPort: 8082
