apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - env:
        - name: jasypt.encryptor.password
          valueFrom:
            configMapKeyRef:
              key: USER_JASYPT_KEY
              name: cloudnine-env
        - name: management.zipkin.tracing.endpoint
          valueFrom:
            configMapKeyRef:
              key: ZIPKIN_URI
              name: cloudnine-env
        - name: eureka.client.service-url.defaultZone
          valueFrom:
            configMapKeyRef:
              key: EUREKA_URI
              name: cloudnine-env
        name: user
        image: fosong98/userservice:0.0.22
        ports:
        - containerPort: 8083
