apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - env:
          - name: jasypt.encryptor.password
            valueFrom:
              configMapKeyRef:
                key: user.jasypt.encryptor.password
                name: cloudnine-env
        name: user
        image: fosong98/userservice:7
        ports:
        - containerPort: 8083
