apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - env:
        - name: jasypt.encryptor.password
          valueFrom:
            configMapKeyRef:
              key: user.jasypt.encryptor.password
              name: cloudnine-env
        - name: management.zipkin.tracing.endpoint
          valueFrom:
            configMapKeyRef:
              key: ZIPKIN_URI
              name: cloudnine-env
        - name: AUTH_SERVICE_URI
          valueFrom:
            configMapKeyRef:
              key: AUTH_SERVICE_URI
              name: cloudnine-env
        - name: CREDIT_SERVICE_URI
          valueFrom:
            configMapKeyRef:
              key: CREDIT_SERVICE_URI
              name: cloudnine-env
        - name: eureka.client.service-url.defaultZone
          valueFrom:
            configMapKeyRef:
              key: EUREKA_URI
              name: cloudnine-env
        name: user
        image: fosong98/userservice:0.0.17
        ports:
        - containerPort: 8083
